# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import database_pb2 as database__pb2

GRPC_GENERATED_VERSION = '1.69.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in database_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DatabaseServiceStub(object):
    """The database service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Get = channel.unary_unary(
                '/flaxkv2.DatabaseService/Get',
                request_serializer=database__pb2.GetRequest.SerializeToString,
                response_deserializer=database__pb2.GetResponse.FromString,
                _registered_method=True)
        self.Set = channel.unary_unary(
                '/flaxkv2.DatabaseService/Set',
                request_serializer=database__pb2.SetRequest.SerializeToString,
                response_deserializer=database__pb2.SetResponse.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/flaxkv2.DatabaseService/Delete',
                request_serializer=database__pb2.DeleteRequest.SerializeToString,
                response_deserializer=database__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.Contains = channel.unary_unary(
                '/flaxkv2.DatabaseService/Contains',
                request_serializer=database__pb2.ContainsRequest.SerializeToString,
                response_deserializer=database__pb2.ContainsResponse.FromString,
                _registered_method=True)
        self.Keys = channel.unary_unary(
                '/flaxkv2.DatabaseService/Keys',
                request_serializer=database__pb2.KeysRequest.SerializeToString,
                response_deserializer=database__pb2.KeysResponse.FromString,
                _registered_method=True)
        self.Info = channel.unary_unary(
                '/flaxkv2.DatabaseService/Info',
                request_serializer=database__pb2.InfoRequest.SerializeToString,
                response_deserializer=database__pb2.InfoResponse.FromString,
                _registered_method=True)


class DatabaseServiceServicer(object):
    """The database service definition
    """

    def Get(self, request, context):
        """Get value by key
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Set(self, request, context):
        """Set key-value pair
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Delete key
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Contains(self, request, context):
        """Check if key exists
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Keys(self, request, context):
        """Get all keys
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Info(self, request, context):
        """Get database info
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DatabaseServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=database__pb2.GetRequest.FromString,
                    response_serializer=database__pb2.GetResponse.SerializeToString,
            ),
            'Set': grpc.unary_unary_rpc_method_handler(
                    servicer.Set,
                    request_deserializer=database__pb2.SetRequest.FromString,
                    response_serializer=database__pb2.SetResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=database__pb2.DeleteRequest.FromString,
                    response_serializer=database__pb2.DeleteResponse.SerializeToString,
            ),
            'Contains': grpc.unary_unary_rpc_method_handler(
                    servicer.Contains,
                    request_deserializer=database__pb2.ContainsRequest.FromString,
                    response_serializer=database__pb2.ContainsResponse.SerializeToString,
            ),
            'Keys': grpc.unary_unary_rpc_method_handler(
                    servicer.Keys,
                    request_deserializer=database__pb2.KeysRequest.FromString,
                    response_serializer=database__pb2.KeysResponse.SerializeToString,
            ),
            'Info': grpc.unary_unary_rpc_method_handler(
                    servicer.Info,
                    request_deserializer=database__pb2.InfoRequest.FromString,
                    response_serializer=database__pb2.InfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'flaxkv2.DatabaseService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('flaxkv2.DatabaseService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DatabaseService(object):
    """The database service definition
    """

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flaxkv2.DatabaseService/Get',
            database__pb2.GetRequest.SerializeToString,
            database__pb2.GetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Set(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flaxkv2.DatabaseService/Set',
            database__pb2.SetRequest.SerializeToString,
            database__pb2.SetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flaxkv2.DatabaseService/Delete',
            database__pb2.DeleteRequest.SerializeToString,
            database__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Contains(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flaxkv2.DatabaseService/Contains',
            database__pb2.ContainsRequest.SerializeToString,
            database__pb2.ContainsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Keys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flaxkv2.DatabaseService/Keys',
            database__pb2.KeysRequest.SerializeToString,
            database__pb2.KeysResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Info(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flaxkv2.DatabaseService/Info',
            database__pb2.InfoRequest.SerializeToString,
            database__pb2.InfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
