# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: database.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'database.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64\x61tabase.proto\x12\x07\x66laxkv2\"\x19\n\nGetRequest\x12\x0b\n\x03key\x18\x01 \x01(\x0c\"+\n\x0bGetResponse\x12\r\n\x05value\x18\x01 \x01(\x0c\x12\r\n\x05\x66ound\x18\x02 \x01(\x08\"(\n\nSetRequest\x12\x0b\n\x03key\x18\x01 \x01(\x0c\x12\r\n\x05value\x18\x02 \x01(\x0c\"\x1e\n\x0bSetResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x1c\n\rDeleteRequest\x12\x0b\n\x03key\x18\x01 \x01(\x0c\"!\n\x0e\x44\x65leteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x1e\n\x0f\x43ontainsRequest\x12\x0b\n\x03key\x18\x01 \x01(\x0c\"\"\n\x10\x43ontainsResponse\x12\x0e\n\x06\x65xists\x18\x01 \x01(\x08\"\x1d\n\x0bKeysRequest\x12\x0e\n\x06prefix\x18\x01 \x01(\t\"\x1c\n\x0cKeysResponse\x12\x0c\n\x04keys\x18\x01 \x03(\x0c\"\r\n\x0bInfoRequest\"Z\n\x0cInfoResponse\x12\x0c\n\x04size\x18\x01 \x01(\x03\x12\x0f\n\x07\x64\x62_path\x18\x02 \x01(\t\x12\x17\n\x0fstorage_backend\x18\x03 \x01(\t\x12\x12\n\nserializer\x18\x04 \x01(\t2\xe7\x02\n\x0f\x44\x61tabaseService\x12\x32\n\x03Get\x12\x13.flaxkv2.GetRequest\x1a\x14.flaxkv2.GetResponse\"\x00\x12\x32\n\x03Set\x12\x13.flaxkv2.SetRequest\x1a\x14.flaxkv2.SetResponse\"\x00\x12;\n\x06\x44\x65lete\x12\x16.flaxkv2.DeleteRequest\x1a\x17.flaxkv2.DeleteResponse\"\x00\x12\x41\n\x08\x43ontains\x12\x18.flaxkv2.ContainsRequest\x1a\x19.flaxkv2.ContainsResponse\"\x00\x12\x35\n\x04Keys\x12\x14.flaxkv2.KeysRequest\x1a\x15.flaxkv2.KeysResponse\"\x00\x12\x35\n\x04Info\x12\x14.flaxkv2.InfoRequest\x1a\x15.flaxkv2.InfoResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'database_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETREQUEST']._serialized_start=27
  _globals['_GETREQUEST']._serialized_end=52
  _globals['_GETRESPONSE']._serialized_start=54
  _globals['_GETRESPONSE']._serialized_end=97
  _globals['_SETREQUEST']._serialized_start=99
  _globals['_SETREQUEST']._serialized_end=139
  _globals['_SETRESPONSE']._serialized_start=141
  _globals['_SETRESPONSE']._serialized_end=171
  _globals['_DELETEREQUEST']._serialized_start=173
  _globals['_DELETEREQUEST']._serialized_end=201
  _globals['_DELETERESPONSE']._serialized_start=203
  _globals['_DELETERESPONSE']._serialized_end=236
  _globals['_CONTAINSREQUEST']._serialized_start=238
  _globals['_CONTAINSREQUEST']._serialized_end=268
  _globals['_CONTAINSRESPONSE']._serialized_start=270
  _globals['_CONTAINSRESPONSE']._serialized_end=304
  _globals['_KEYSREQUEST']._serialized_start=306
  _globals['_KEYSREQUEST']._serialized_end=335
  _globals['_KEYSRESPONSE']._serialized_start=337
  _globals['_KEYSRESPONSE']._serialized_end=365
  _globals['_INFOREQUEST']._serialized_start=367
  _globals['_INFOREQUEST']._serialized_end=380
  _globals['_INFORESPONSE']._serialized_start=382
  _globals['_INFORESPONSE']._serialized_end=472
  _globals['_DATABASESERVICE']._serialized_start=475
  _globals['_DATABASESERVICE']._serialized_end=834
# @@protoc_insertion_point(module_scope)
